apiVersion: v1
kind: ConfigMap
metadata:
  name: cicd-web-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ci-cd-web.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  WELCOME_MESSAGE: {{ .Values.config.WELCOME_MESSAGE | quote }}