{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cicd-web-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ci-cd-web.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.secret.stringData }}
{{- toYaml .Values.secret.stringData | nindent 2 }}
{{- else }}
  {}
{{- end }}
{{- end }}